### PR TITLE
adding clustering for river example

### PR DESCRIPTION
**Pull request by big-c-note**
A small example of the river clustering. Now that I have the centroids, I can compute clusters based on the EMD of the turn/river, so I'll start that next, just as small examples. 

I'm not entirely sure the best way to store/compute the combos, and I need to figure out how to get lossless combos of hands. For example, there are about 2.5 billion lossless combos of our_hand, flop, turn, river, and the way I'm calculating expected hand strength is by simulating 25 random opponent hands (probably should be more). At 2.5 billion records that will take a while..

Happy to get any feedback, thanks @fedden 

https://github.com/fedden/pluribus-poker-AI/blob/feature/WIP-clustering-infosets/research/clustering/clustering_infosets.ipynb
https://github.com/fedden/pluribus-poker-AI/blob/feature/WIP-clustering-infosets/research/size_of_problem/size_of_problem.ipynb

### CODE REVIEW

**Comment by Slowly-Grokking** [comment]
I have some idle GPUs if I can be of any help...  Unfortunately, I'm more of a bodger than a programmer, but I'd love to help in anyway I can.

**Comment by fedden** [comment]
Thanks @Slowly-Grokking that is very kind and we'll let you know! I have a couple 1080Ti too but the paper doesn't even make use of them so not sure how useful they'll be. What we'll need is a very high RAM instance >= 128GB

**Comment by fedden** [comment]
@big-c-note I've taken a look at the notebooks and whilst it makes things like hacking together ideas and plotting super easy, WRT this PR it's difficult to ensure I call things in the right order to reproduce, and also leave comments on your logic via GitHub. 

If you are happy with the logic and you can put it into a regular script it would make it a lot easier for me to help out on! This is generally what I do for my research - hack first in a notebook, refactor ideas into a single cell, then copy and paste cell into a script.

Also, **please feel free to ignore this** if you feel this is totally undue work, I don't want to waste your time at all!

**Comment by big-c-note** [comment]
@fedden I might keep trucking through the flop clusters then add to a script. I also have a similar workflow to you for research. 

I would like to merge this into develop at some point - what format is best? Should all PRs to develop be a script rather than notebook? I'm fine with that if it keeps things pro.

**Comment by fedden** [comment]
It's completely up to you. I'm totally happy for you to merge this now if you want, or, If you want to add flop clustering to a script then add it to this PR, I'll take a look at those scripts and run them locally and leave feedback then.

I'm happy to merge notebooks to the repo, it's just tricky for me to leave meaningful feedback on them using github's UI. 

I'll follow your lead here, if you don't want to do any more here, just merge, or, if you push any scripts, I'll check them out asap

**Comment by big-c-note** [comment]
Ok sounds good, thanks! Going to let it sit for a bit

**Comment by big-c-note** [comment]
Decided to merge to keep myself organized, will finish the other two in notebook form and refactor into a script

**Pull request merged**
