### PR TITLE
Finishing ranking script (for now). Looks like it's working!

### PR DESCRIPTION
**Pull request by fedden**
Adds a script that looks like the following and dumps a file at the end of the rankings:

Screenshot 2020-02-21 at 12 33 21

### CODE REVIEW

**Comment by big-c-note** [comment]
It works great, but I had to change the following in research/preflop_hand_ranking/monte_carlo_rank.py:

From:
` 128. rank_0 = hand[0].rank_int - 2`
`129. rank_1 = hand[1].rank_int - 2`

To:
` 128. rank_0 = hand[0].rank_int() - 2`
`129. rank_1 = hand[1].rank_int() - 2`


Was getting the following error running `python monte_carlo_rank.py` with the previous:
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
```
File "/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
```
```
File "/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
```
```
File "research/preflop_hand_ranking/monte_carlo_rank.py", line 157, in delta_matrix_worker
    delta_matrix = evaluator(n_players=n_players)
```
 ```
File "research/preflop_hand_ranking/monte_carlo_rank.py", line 61, in __call__
    delta_matrix = self._compute_delta_matrix(rank_to_hands)
```
 ```
File "research/preflop_hand_ranking/monte_carlo_rank.py", line 130, in _compute_delta_matrix
    rank_0 = hand[0].rank_int - 2
```
`TypeError: unsupported operand type(s) for -: 'method' and 'int'`


Might be me though as I was able to call `card.rank_int` from my terminal
```
>>> from pluribus.game.deck import *
>>> deck=Deck()
>>> deck
<pluribus.game.deck.Deck object at 0x10c8424e0>
>>> deck.pick
<bound method Deck.pick of <pluribus.game.deck.Deck object at 0x10c8424e0>>
>>> deck.pick()
<Card card=[ace of hearts ♥]>
>>> card = deck.pick()
>>> from pluribus.game.card import *
>>> card
<Card card=[king of hearts ♥]>
>>> card.rank_int - 2
11
```

**Comment by fedden** [comment]
@big-c-note what version of python are you using? Although I’ve defined the rank_int as a method it is decorated as a public attribute do you shouldn’t need to add parentheses ()

**Comment by big-c-note** [comment]
@fedden , ok probably just need to get Anaconda off my PATH, I am on a different computer than I usually work on, so I think it's not using the virtual environment I have set up.

**Comment by big-c-note** [comment]
@fedden it's 3.7+

**Comment by big-c-note** [comment]
Yeah that was it, there was just a lot of garbage on my PATH

**Comment by fedden** [comment]
Okay gonna merge it in hopefully that’s cool with you

**Comment by big-c-note** [comment]
all good

**Pull request merged**
