### PR TITLE
WIP: Implement Kuhn poker game in tree-like format

### PR DESCRIPTION
**Pull request by fedden**
In this work in progress PR I'll implement the ideas from the "An Introduction to Counterfactual Regret Minimization" paper, that can be used as a spring board to prototype and redesign the pluribus game engine to support recursive depth-first game tree traversal.

### CODE REVIEW

**Comment by big-c-note** [comment]
@fedden, just keep in mind that the example I shared previously uses perfect recall (if I remember correctly), but we'll be using imperfect recall for tree traversal if I'm understanding everything right, as I'm sure you are

**Comment by fedden** [comment]
Thanks @big-c-note I’ll add it as an exercise to implement support for both perfect and imperfect recall, which looks like it’s just down to how I make use of the history of actions.

Really I just want to add this as a test run in game tree design before tackling the more complex Texas Holdem refactor. It’s easier to bake a three layer cake if you’ve baked a simple one layer cake before!

**Comment by fedden** [comment]
Hmm so my agent is learning a strategy for the given infoset that looks like this: 
```
 * info set <hand=[2], actions=[]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[2], actions=[bet]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[2], actions=[check, bet]> strategy: {'check': 1.0, 'bet': 0.0}
 * info set <hand=[2], actions=[check]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[3], actions=[]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[3], actions=[bet]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[3], actions=[check, bet]> strategy: {'check': 1.0, 'bet': 0.0}
 * info set <hand=[3], actions=[check]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[4], actions=[]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[4], actions=[bet]> strategy: {'check': 0.5, 'bet': 0.5}
 * info set <hand=[4], actions=[check, bet]> strategy: {'check': 0.0, 'bet': 1.0}
 * info set <hand=[4], actions=[check]> strategy: {'check': 0.5, 'bet': 0.5}
```

**Comment by fedden** [comment]
I'm not sure that's quite right in terms of learning the optimal strategy.

**Comment by big-c-note** [comment]
Based on your note above:
```* info set <hand=[3], actions=[check, bet]> strategy: {'check': 1.0, 'bet': 0.0}```

I'm reading "check" in this instance as "fold". Assuming that the other player is betting their [2] some proportion of the time, they should be having a mixed strategy here. However, this would be optimal if player 2 always bet their [4] after a check and always folded their [2] after a check. So, it may be right, but it's dependent on the other player I think?

But for this:
```* info set <hand=[4], actions=[check]> strategy: {'check': 0.5, 'bet': 0.5}```
I don't see a reason to ever check in this spot. That would be a terminal node right ```[check, check]```? They have the best hand possible and they are giving up the chance to win a bet from their opponent.

**Comment by fedden** [comment]
Closing as have renamed branch

**Pull request closed without merging**
