### PR TITLE
WIP: Add pre-flop ranking

### PR DESCRIPTION
**Pull request by fedden**

### CODE REVIEW

**Comment by big-c-note** [comment]
looks good

**Comment by fedden** [comment]
Oh @big-c-note thank you for the PR review but please allow me to merge in my branches - not a big deal but if I label something WIP then that means work in progress and I’m sharing it for visibility, but it should not be merged yet.

Generally I will reach out to you to slack for a PR review, and if it passes your inspection and the tests pass then I will merge it when I think it’s ready. 

Likewise if you have a PR then please just ask me for a review and when I give it the green light you can merge it when you have finalised everything.

**Comment by fedden** [comment]
Also this merged into master (my fault for mistakenly setting that) which we don’t want to do, really we should merge into develop regularly and when we meet some milestone and are happy with the stability of things we should merge to develop and make a release tag

**Comment by fedden** [comment]
I’ll make sure all the branches are aligned by the end of day, and I will also make a development process document that will help to manage git. I will also make the default branch into develop to prevent accidental merges into master

**Comment by big-c-note** [comment]
@fedden , oh shoot, my bad!!! I thought you left it for me after our convo on slack, and it seemed innocuous. But I'm with you now, thanks for letting me know and getting it back to normal - apologies for that.

**Comment by fedden** [comment]
Not a problem at all!

**Pull request merged**
